# Generated by Django 3.2.2 on 2025-12-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UlinziTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('resident', 'Resident'), ('authority', 'Authority'), ('officer', 'Officer'), ('chief', 'Area Chief'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
