# Generated by Django 3.2.2 on 2025-12-05 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UlinziTracker', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('resident', 'Resident'), ('authority', 'Authority'), ('officer', 'Officer'), ('chief', 'Area Chief'), ('admin', 'Admin')], default='resident', max_length=20),
        ),
    ]
