# Generated by Django 3.2.2 on 2025-12-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UlinziTracker', '0003_auto_20251205_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='incident_audio/'),
        ),
        migrations.AddField(
            model_name='incident',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='incident_docs/'),
        ),
        migrations.AddField(
            model_name='incident',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='incident_images/'),
        ),
        migrations.AddField(
            model_name='incident',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='incident_videos/'),
        ),
    ]
